version: '3.8'

services:
  api:
    container_name: node_assignment
    restart: always
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  client:
    container_name: react_app
    restart: always
    build:
      context: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  data: {}